### PR TITLE
samclassix-redeem-wfps

### PR DESCRIPTION
**Pull request by samclassix**
https://github.com/Frankencoin-ZCHF/frankencoin-dapp/issues/63

### CODE REVIEW

**Comment by samclassix** [comment]
Screenshot 2024-09-18 at 1 08 41 PM
Screenshot 2024-09-18 at 1 09 04 PM
Screenshot 2024-09-18 at 1 09 34 PM

**Comment by luziusmeisser** [comment]
Thanks, very nice!

Would it be possible to adjust the colors of the following three items:
image

- I think we should remove the | separator completely or make it the same color as the background. It is not needed.
- The bright blue of the selected item should be replaced with the light blue that we already use in our palette
- The chevron should stay visible after selecting an item, now it almost disappears as it is only slightly brighter than the background

Not sure if this is configurable in this selector. :)

**Comment by luziusmeisser** [comment]
PS: den leuchtblauen selection-Rahmen kann man ev. auch ganz verstecken. Hat ohnehin eine andere Form als die Text Box und passt von daher nicht gut.

**Comment by samclassix** [comment]
Screenshot 2024-09-23 at 9 36 30 AM

**Review by luziusmeisser — APPROVED** [review]
Thanks, looks good!

**Review by TaprootFreak — DISMISSED** [review]

**Review by TaprootFreak — APPROVED** [review]

**Pull request merged**
